import { useEffect, useMemo, useState } from 'react';import { createInitialBoard } from './game/initialBoard';import { createGameState } from './game/gameState';import { applyMove, checkWinner, getLegalMoves } from './game/rules';import { Move, Piece } from './game/types';import { pickAIMove } from './game/ai';import GameBoard from './components/GameBoard';import SidePanel from './components/SidePanel';import GameModePanel from './components/GameModePanel';import RuleModal from './components/RuleModal';
export default function App(){const [board,setBoard]=useState<Piece[]>(createInitialBoard());const [state,setState]=useState(createGameState('pvp'));const [sel,setSel]=useState<string>();const [legal,setLegal]=useState<Move[]>([]);const [rulesOpen,setRules]=useState(false);const [history,setHistory]=useState<{b:Piece[];s:any}[]>([]);
const turnPieces=useMemo(()=>board.filter(p=>p.alive&&p.side===state.turn),[board,state.turn]);
useEffect(()=>{const w=checkWinner(board,state); if(w) setState(s=>({...s,winner:w}));},[board,state]);
useEffect(()=>{if(state.winner) return;const aiTurn=(state.mode==='pve'&&state.turn==='blue')||state.mode==='demo'; if(!aiTurn)return; const t=setTimeout(()=>{const m=pickAIMove(board,{...state}); if(m) move(m);},650); return()=>clearTimeout(t);},[board,state.turn,state.mode,state.ai,state.winner]);
const select=(id:string)=>{const p=board.find(x=>x.id===id&&x.alive); if(!p||p.side!==state.turn) return; setSel(id); setLegal(getLegalMoves(board,p,state));};
const move=(m:Move)=>{setHistory(h=>[...h,{b:board.map(x=>({...x})),s:JSON.parse(JSON.stringify(state))}]); const ns={...state,captured:{red:[...state.captured.red],blue:[...state.captured.blue]},moves:[...state.moves]};const nb=applyMove(board,m,ns); setBoard(nb); setState(ns); setSel(undefined); setLegal([]);};
const restart=()=>{setBoard(createInitialBoard());setState(createGameState(state.mode));setHistory([]);setSel(undefined);setLegal([])};
const undo=()=>{const last=history.at(-1); if(!last) return; setBoard(last.b); setState(last.s); setHistory(h=>h.slice(0,-1));};
return <div className='wrap'><main><h1>《森林斗兽棋》</h1><GameModePanel mode={state.mode} setMode={m=>{setState(s=>({...createGameState(m),ai:s.ai}));setBoard(createInitialBoard());}} ai={state.ai} setAi={d=>setState(s=>({...s,ai:d}))}/><GameBoard board={board} sel={sel} moves={legal} onSelect={select} onMove={move}/>{state.winner&&<div className='winner'>胜利方：{state.winner}</div>}</main><SidePanel state={state} onRestart={restart} onUndo={undo} onRules={()=>setRules(true)}/><RuleModal open={rulesOpen} onClose={()=>setRules(false)}/></div>}
