import { useEffect, useState } from 'react';import { createInitialBoard } from './game/initialBoard';import { createGameState } from './game/gameState';import { applyMove, checkWinner, getLegalMoves } from './game/rules';import { Move, Piece } from './game/types';import { pickAIMove } from './game/ai';import GameBoard from './components/GameBoard';import SidePanel from './components/SidePanel';import GameModePanel from './components/GameModePanel';import RuleModal from './components/RuleModal';
const beep=(f:number,d=0.08)=>{const ctx=new (window.AudioContext||(window as any).webkitAudioContext)();const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=f;o.connect(g);g.connect(ctx.destination);g.gain.value=0.04;o.start();o.stop(ctx.currentTime+d)};
const RuleSection=()=> <section className='rulesSec'><h2>📖 斗兽棋游戏规则</h2><div className='ruleGrid'><div className='panel'><h4>游戏目标</h4><ul><li>进入对方兽穴立即获胜</li><li>吃光对方棋子获胜</li><li>对方无合法走法则获胜</li></ul></div><div className='panel'><h4>动物等级</h4><p>象8 狮7 虎6 豹5 狼4 狗3 猫2 鼠1（同级可互吃）</p></div><div className='panel'><h4>河流与跳跃</h4><ul><li>仅鼠可入河</li><li>狮虎可跳河</li><li>河中有鼠会阻挡狮虎跳河</li></ul></div><div className='panel'><h4>特殊规则</h4><ul><li>鼠可吃象</li><li>象默认不可吃鼠（可切换）</li><li>敌方进我方陷阱后战力视为0</li></ul></div></div></section>;
export default function App(){const loaded=(()=>{try{return JSON.parse(localStorage.getItem('fjc-save')||'null')}catch{return null}})();const [board,setBoard]=useState<Piece[]>(loaded?.board||createInitialBoard());const [state,setState]=useState(loaded?.state||createGameState('pvp'));const [sel,setSel]=useState<string>();const [legal,setLegal]=useState<Move[]>([]);const [rulesOpen,setRules]=useState(false);const [history,setHistory]=useState<{b:Piece[];s:any}[]>([]);const [flash,setFlash]=useState('');const [last,setLast]=useState<Move|undefined>();const [thinking,setThinking]=useState(false);
useEffect(()=>{localStorage.setItem('fjc-save',JSON.stringify({board,state}));},[board,state]);
useEffect(()=>{const w=checkWinner(board,state); if(w) {setState(s=>({...s,winner:w})); beep(660,0.2);} },[board,state]);
useEffect(()=>{if(state.winner) return;const aiTurn=(state.mode==='pve'&&state.turn==='blue')||state.mode==='demo'; if(!aiTurn)return; setThinking(true); const t=setTimeout(()=>{const m=pickAIMove(board,{...state}); setThinking(false); if(m) move(m);},700); return()=>clearTimeout(t);},[board,state.turn,state.mode,state.ai,state.winner]);
const select=(id:string)=>{const p=board.find(x=>x.id===id&&x.alive); if(!p||p.side!==state.turn) return; setSel(id); setLegal(getLegalMoves(board,p,state));};
const move=(m:Move)=>{setHistory(h=>[...h,{b:board.map(x=>({...x})),s:JSON.parse(JSON.stringify(state))}]); const ns={...state,captured:{red:[...state.captured.red],blue:[...state.captured.blue]},moves:[...state.moves]};const nb=applyMove(board,m,ns); setBoard(nb); setState(ns); setLast(m);setSel(undefined); setLegal([]); if(m.jump){setFlash('狮虎跳河！');beep(520,0.12);beep(780,0.15);} else if(m.captureId){setFlash('捕猎成功，额外回合！');beep(460,0.09);beep(620,0.11);} else beep(330,0.05); setTimeout(()=>setFlash(''),700);};
const restart=()=>{setBoard(createInitialBoard());setState(createGameState(state.mode));setHistory([]);setSel(undefined);setLegal([])};const undo=()=>{const last=history.at(-1); if(!last) return; setBoard(last.b); setState(last.s); setHistory(h=>h.slice(0,-1));};
return <><header className='topbar'><div className='brand'>🦁 斗兽棋</div><nav><button onClick={()=>setRules(true)}>规则</button></nav></header><div className='wrap'><main className='mainCard'><div className='versus'><span className='blueTag'>蓝方</span><b>VS</b><span className='redTag'>红方</span></div><GameModePanel mode={state.mode} setMode={m=>{setState(s=>({...createGameState(m),ai:s.ai,config:s.config}));setBoard(createInitialBoard());}} ai={state.ai} setAi={d=>setState(s=>({...s,ai:d}))} config={state.config} setConfig={c=>setState(s=>({...s,config:c}))}/>{thinking&&<div className='ai'>AI 正在思考...</div>}{flash&&<div className='fx'>{flash}</div>}<div className='boardFrame'><GameBoard board={board} sel={sel} moves={legal} last={last} onSelect={select} onMove={move}/></div>{state.extraTurn&&<div className='extra'>连击奖励：{state.extraTurn==='red'?'红方':'蓝方'}再走一步</div>}{state.winner&&<div className='winner'>胜利方：{state.winner}</div>}</main><SidePanel state={state} onRestart={restart} onUndo={undo} onRules={()=>setRules(true)}/><RuleModal open={rulesOpen} onClose={()=>setRules(false)}/></div><RuleSection/></>}
