import { useEffect, useState } from 'react';import { createInitialBoard } from './game/initialBoard';import { createGameState } from './game/gameState';import { applyMove, checkWinner, getLegalMoves } from './game/rules';import { CardType, Move, Piece, PieceType } from './game/types';import { pickAIMove } from './game/ai';import GameBoard from './components/GameBoard';import SidePanel from './components/SidePanel';import GameModePanel from './components/GameModePanel';import RuleModal from './components/RuleModal';import { RANK } from './game/constants';
const CN:Record<PieceType,string>={elephant:'象',lion:'狮',tiger:'虎',leopard:'豹',wolf:'狼',dog:'狗',cat:'猫',rat:'鼠'};
const beep=(f:number,d=0.08)=>{const ctx=new (window.AudioContext||(window as any).webkitAudioContext)();const o=ctx.createOscillator(),g=ctx.createGain();o.frequency.value=f;o.connect(g);g.connect(ctx.destination);g.gain.value=0.04;o.start();o.stop(ctx.currentTime+d)};
const RuleSection=()=> <section className='rulesSec'><h2>📖 斗兽棋游戏规则</h2><div className='ruleGrid'><div className='panel ruleCard'><h4>🎯 游戏目标</h4><p>斗兽棋是一款经典策略棋类。目标是进入对方兽穴，或吃光对方棋子。</p></div><div className='panel ruleCard'><h4>🦁 动物等级</h4><p>象8 狮7 虎6 豹5 狼4 狗3 猫2 鼠1；同级可互吃。</p></div><div className='panel ruleCard'><h4>🎮 移动规则</h4><ul><li>每次走一步（狮虎可跳河）</li><li>不能斜走，不能进己方兽穴</li><li>吃子后可选择变身，但不能再走一步</li></ul></div><div className='panel info blue'><h4>✨ 新技能与卡牌</h4><p>连击（吃子后追加1回合）、光盾（首次受击免伤）、潜行（未主动攻击前不可被吃）。每方初始各1张，可对己方任意存活棋子使用。</p></div><div className='panel info cyan'><h4>🏆 胜负判定</h4><p>进敌穴胜、吃光胜、对方无路可走胜、80回合无吃子可判和。</p></div></div></section>;
export default function App(){const loaded=(()=>{try{return JSON.parse(localStorage.getItem('fjc-save')||'null')}catch{return null}})();const [board,setBoard]=useState<Piece[]>(loaded?.board||createInitialBoard());const [state,setState]=useState(loaded?.state?{...loaded.state,powerUsed:loaded.state.powerUsed||[]}:createGameState('pvp'));const [sel,setSel]=useState<string>();const [legal,setLegal]=useState<Move[]>([]);const [rulesOpen,setRules]=useState(false);const [history,setHistory]=useState<{b:Piece[];s:any}[]>([]);const [flash,setFlash]=useState('');const [last,setLast]=useState<Move|undefined>();const [thinking,setThinking]=useState(false);const [morph,setMorph]=useState<{pieceId:string;type:PieceType}|null>(null);
useEffect(()=>{localStorage.setItem('fjc-save',JSON.stringify({board,state}));},[board,state]);
useEffect(()=>{const w=checkWinner(board,state); if(w) {setState(s=>({...s,winner:w})); beep(660,0.2);} },[board,state]);
useEffect(()=>{if(state.winner||morph) return;const aiTurn=(state.mode==='pve'&&state.turn==='blue')||state.mode==='demo'; if(!aiTurn)return; setThinking(true); const t=setTimeout(()=>{const m=pickAIMove(board,{...state}); setThinking(false); if(m) move(m);},700); return()=>clearTimeout(t);},[board,state.turn,state.mode,state.ai,state.winner,morph]);
const select=(id:string)=>{const p=board.find(x=>x.id===id&&x.alive); if(!p||p.side!==state.turn) return; setSel(id); setLegal(getLegalMoves(board,p,state));};
const move=(m:Move)=>{const captured=board.find(x=>x.id===m.captureId);setHistory(h=>[...h,{b:board.map(x=>({...x})),s:JSON.parse(JSON.stringify(state))}]); const ns={...state,captured:{red:[...state.captured.red],blue:[...state.captured.blue]},moves:[...state.moves]};const nb=applyMove(board,m,ns); setBoard(nb); setState(ns); setLast(m);setSel(undefined); setLegal([]); if(m.jump){setFlash('狮虎跳河！');beep(520,0.12);beep(780,0.15);} else if(m.captureId){setFlash('捕猎成功！可选择变身（不额外行动）');beep(460,0.09);beep(620,0.11); if(captured) setMorph({pieceId:m.pieceId,type:captured.type});} else beep(330,0.05); setTimeout(()=>setFlash(''),700);};
const restart=()=>{setBoard(createInitialBoard());setState(createGameState(state.mode));setHistory([]);setSel(undefined);setLegal([])};const undo=()=>{const last=history.at(-1); if(!last) return; setBoard(last.b); setState(last.s); setHistory(h=>h.slice(0,-1));};
const useCard=(card:CardType)=>{if(!sel)return;const i=board.findIndex(p=>p.id===sel&&p.side===state.turn&&p.alive); if(i<0)return; if(!state.cards[state.turn].includes(card))return; const t=board[i]; if((card==='shield'&&t.shield)||(card==='stealth'&&t.stealth)||(card==='combo'&&t.combo)){setFlash('该棋子已拥有此技能');setTimeout(()=>setFlash(''),700);return;} setHistory(h=>[...h,{b:board.map(x=>({...x})),s:JSON.parse(JSON.stringify(state))}]);const nb=board.map(p=>({...p})); if(card==='shield') nb[i].shield=true; if(card==='stealth') nb[i].stealth=true; if(card==='combo') nb[i].combo=true; const ns={...state,cards:{red:[...state.cards.red],blue:[...state.cards.blue]}}; const hand=ns.cards[state.turn]; hand.splice(hand.indexOf(card),1); setBoard(nb); setState(ns); setFlash(`已为${CN[t.type]}附加${card==='shield'?'光盾':card==='stealth'?'潜行':'连击'}`);beep(700,0.09);setTimeout(()=>setFlash(''),800);};
const doMorph=(yes:boolean)=>{if(yes&&morph){setBoard(b=>b.map(p=>p.id===morph.pieceId?{...p,type:morph.type,rank:RANK[morph.type]}:p));beep(840,0.12);} setMorph(null);};
return <><header className='topbar'><div className='brand'>🦁 斗兽棋</div><nav><button onClick={()=>setRules(true)}>规则</button></nav></header><div className='wrap'><main className='mainCard'><div className='versus'><span className='blueTag'>蓝方</span><b>VS</b><span className='redTag'>红方</span></div><GameModePanel mode={state.mode} setMode={m=>{setState(s=>({...createGameState(m),ai:s.ai,config:s.config}));setBoard(createInitialBoard());}} ai={state.ai} setAi={d=>setState(s=>({...s,ai:d}))} config={state.config} setConfig={c=>setState(s=>({...s,config:c}))}/>{thinking&&<div className='ai'>AI 正在思考...</div>}{flash&&<div className='fx burst'>{flash}</div>}<div className='boardArena'><div className='capSide blue'><b>蓝方被吃</b><div className='miniList'>{state.captured.blue.length?state.captured.blue.map((p,i)=><span key={i} className='mini'>{CN[p.type]}</span>):'无'}</div></div><div className='boardFrame'><GameBoard board={board} sel={sel} moves={legal} last={last} onSelect={select} onMove={move}/></div><div className='capSide red'><b>红方被吃</b><div className='miniList'>{state.captured.red.length?state.captured.red.map((p,i)=><span key={i} className='mini'>{CN[p.type]}</span>):'无'}</div></div></div>{state.winner&&<div className='winner'>胜利方：{state.winner}</div>}</main><SidePanel state={state} selected={board.find(p=>p.id===sel)} onUseCard={useCard} onRestart={restart} onUndo={undo} onRules={()=>setRules(true)}/><RuleModal open={rulesOpen} onClose={()=>setRules(false)}/></div><RuleSection/>{morph&&<div className='modal'><div className='panel'><h3>是否变身为 {CN[morph.type]} ？</h3><div className='row'><button onClick={()=>doMorph(true)}>变身</button><button onClick={()=>doMorph(false)}>保持原形</button></div></div></div>}</>}
