import { useEffect, useMemo, useState } from 'react';
import Layout from './components/Layout';import LevelCard from './components/LevelCard';import { levels } from './data/levels';import ResultCertificate from './components/ResultCertificate';
import { allLevels } from './levels/Levels';import { createSeededRandom, randomChoice, randomInt } from './utils/random';
export default function App(){const [globalSeed,setGlobalSeed]=useState(()=>Date.now());const [currentLevel,setCurrentLevel]=useState(1);const [failCount,setFail]=useState(0);const [hintCount,setHint]=useState(0);const [skipCount,setSkip]=useState(0);const [startTime,setStart]=useState(Date.now());const [elapsedTime,setElapsed]=useState(0);const [passedLevels,setPassed]=useState<number[]>([]);const [prankCount,setPrank]=useState(0);const [toast,setToast]=useState('');const [shake,setShake]=useState(false);
const levelSeed=useMemo(()=>{const rng=createSeededRandom(globalSeed+currentLevel*1009);return randomInt(1000,999999,rng);},[globalSeed,currentLevel]);
const event=useMemo(()=>{const rng=createSeededRandom(levelSeed+77);return {rename:rng()>0.7,jitter:rng()>0.6,sus:rng()>0.7,scan:randomInt(8,22,rng)};},[levelSeed]);
useEffect(()=>{const t=setInterval(()=>setElapsed(Math.floor((Date.now()-startTime)/1000)),1000);return()=>clearInterval(t)},[startTime]);
const elapsed=useMemo(()=>`${Math.floor(elapsedTime/60)}:${String(elapsedTime%60).padStart(2,'0')}`,[elapsedTime]);
const restart=()=>{setGlobalSeed(Date.now()+Math.floor(Math.random()*9999));setCurrentLevel(1);setFail(0);setHint(0);setSkip(0);setPrank(0);setPassed([]);setStart(Date.now());setElapsed(0);};
if(currentLevel>12)return <div className='app'><ResultCertificate elapsed={elapsed} fail={failCount} hint={hintCount} skip={skipCount} prank={prankCount} onRestart={restart}/></div>;
const L=allLevels[currentLevel-1];const meta=levels[currentLevel-1];
return <Layout level={currentLevel} total={12} elapsed={elapsed} fails={failCount} desc={meta.description} onRestart={restart} onSkip={()=>{setSkip(v=>v+1);setCurrentLevel(v=>v+1);}} hints={meta.hints} addHint={()=>setHint(v=>v+1)} scanSpeed={event.scan}><LevelCard shake={shake}><h2>{meta.title}</h2>{event.sus&&<p className='hint'>系统随机怀疑：你今天点击节奏非常可疑。</p>}<L levelSeed={levelSeed} randomEvent={event} onPass={()=>{setPassed(v=>[...v,currentLevel]);setCurrentLevel(v=>v+1);setToast('✅ 验证通过');}} onFail={(m)=>{setFail(v=>v+1);setToast(`❌ ${m}`);setShake(true);setTimeout(()=>setShake(false),350);}} onPrank={(m)=>{setPrank(v=>v+1);setToast(`🤖 ${m}`);} } addHint={()=>setHint(v=>v+1)} /></LevelCard>{toast&&<div className='toast'>{toast}</div>}</Layout>}
