import { useEffect, useMemo, useState } from 'react';
import { Template } from '../engine/levelTypes';
import { createSeededRandom, randomChoice, randomInt } from '../engine/random';
import TrapLayer from './TrapLayer';
import ButtonField from './ButtonField';
import { nextPrank } from '../engine/prankEvents';

type P={level:Template;seed:number;difficulty:number;onPass:()=>void;onFail:(m:string,r?:boolean)=>void;onPrank:(m:string)=>void};

function ButtonFlood({level,seed,onPass,onFail}:P){const rng=useMemo(()=>createSeededRandom(seed),[seed]);const target=level.task.match(/“(.+)”/)?.[1]||'继续';return <div><h3>任务：{level.task}</h3><ButtonField target={target} rng={rng} onHitTrue={onPass} onHitFalse={()=>onFail('你点到了一个过于积极的按钮。',true)}/></div>}
function InputCorruption({level,seed,onPass,onFail}:P){const rng=useMemo(()=>createSeededRandom(seed),[seed]);const code=useMemo(()=>randomChoice(['HUMAN','NOTBOT','IAMREAL','NOAI','TRUSTME'],rng),[rng]);const mode=useMemo(()=>randomChoice(['lower','space','reverse','drop'],rng),[rng]);const [fixed,setFixed]=useState(false);const [v,setV]=useState('');const mutate=(x:string)=>fixed?x:mode==='lower'?x.toLowerCase():mode==='space'?x.split('').join(' '):mode==='reverse'?x.split('').reverse().join(''):x.slice(0,-1);const sw=useMemo(()=>['关闭自动纠正','启用智能改写','自动修正增强','省心输入模式'].sort(()=>rng()-0.5),[rng]);return <div><h3>任务：{level.task}</h3><p>验证码：{code}</p><input value={v} onChange={e=>setV(mutate(e.target.value))}/><div className='row'>{sw.map(s=><button key={s} className='btn subtle' onClick={()=>s==='关闭自动纠正'?setFixed(true):onFail('输入内容在进入系统前发生了变化。',true)}>{s}</button>)}</div><button className='btn' onClick={()=>v===code?onPass():onFail('输入内容在进入系统前发生了变化。')}>验证</button></div>}
function PathAvoid({level,seed,difficulty,onPass,onFail}:P){const rng=useMemo(()=>createSeededRandom(seed),[seed]);const traps=useMemo(()=>Array.from({length:3+difficulty},()=>({x:randomInt(30,430,rng),y:randomInt(50,230,rng),w:randomInt(70,130,rng),h:24})),[rng,difficulty]);return <div className='path'><h3>任务：{level.task}</h3><TrapLayer traps={traps} onHit={()=>onFail('你踩到了系统画出来的坑。',true)}/><button className='btn target' style={{position:'absolute',right:20,bottom:20}} onClick={onPass}>目标按钮</button></div>}
function SliderTrap({level,seed,onPass,onFail,onPrank}:P){const rng=useMemo(()=>createSeededRandom(seed),[seed]);const trap=useMemo(()=>[randomInt(25,45,rng),randomInt(55,75,rng)] as const,[rng]);const [v,setV]=useState(0);const [b,setB]=useState(0);const [safe,setSafe]=useState(false);useEffect(()=>{const id=setInterval(()=>setSafe(s=>!s),1200);return()=>clearInterval(id)},[]);return <div><h3>任务：{level.task}</h3><div className='track'><div className={`red ${safe?'safe':''}`} style={{left:`${trap[0]}%`,width:`${trap[1]-trap[0]}%`}}/></div><input type='range' min={0} max={100} value={v} onChange={e=>{let n=+e.target.value;if(n>85)n=Math.min(100,v+2);if(n>trap[0]&&n<trap[1]&&!safe){setB(x=>x+1);setV(Math.max(0,n-25));onPrank('滑块被路障弹回');if(b>=2)onFail('红区硬闯次数过多。',true);return;}setV(n);if(n===100)onPass();}}/></div>}

export default function LevelRenderer(p:P){const prank=useMemo(()=>nextPrank(createSeededRandom(p.seed+999)),[p.seed]);const [tempDisabled,setTempDisabled]=useState(prank.disabled);useEffect(()=>{if(!prank.disabled)return;const t=setTimeout(()=>setTempDisabled(false),800);return()=>clearTimeout(t)},[prank.disabled]);
return <div className='levelWrap'>{prank.bubble&&<div className='bubble'>安全提示遮挡中…</div>}{tempDisabled&&<div className='overlayMini'>按钮冷静中</div>}{p.level.type==='button_flood'?<ButtonFlood {...p}/>:p.level.type==='input_corruption'?<InputCorruption {...p}/>:p.level.type==='path_avoidance'?<PathAvoid {...p}/>:p.level.type==='slider_trap'?<SliderTrap {...p}/>:<div><h3>任务：{p.level.task}</h3><button className='btn' onClick={p.onPass}>完成</button></div>}</div>}
