import { useEffect, useMemo, useState } from 'react';
import { LevelProps } from './common';
import { clamp, createSeededRandom, randomChoice, randomInt, shuffle } from '../utils/random';

export function Level1Checkbox({ levelSeed, onPass, onFail }: LevelProps) {
  // 任务: 点击复选框；整蛊: 靠近时缓慢移动最多4次；通过: 移动结束后点击。
  const rng = useMemo(() => createSeededRandom(levelSeed), [levelSeed]);
  const [moves, setMoves] = useState(0); const [miss, setMiss] = useState(0); const [msg, setMsg] = useState('');
  const lines = ['别急，我有点紧张。', '你靠得太快了。', '让我确认一下你是不是手抖。'];
  const [pos, setPos] = useState({ x: randomInt(-60, 60, rng), y: randomInt(-20, 20, rng) });
  return <div><h3>任务：点击“我不是机器人”复选框</h3><div className='feedback'>{msg || '提示：慢慢靠近它。'}</div><div className='levelBox' onClick={(e)=>{if(e.target===e.currentTarget){const c=miss+1;setMiss(c);if(c>=3) onFail('点击过于急躁，请像人类一样靠近。',{resetLevel:true});}}} onMouseMove={(e)=>{if(moves>=4)return; const r=e.currentTarget.getBoundingClientRect(); const nx=clamp(pos.x+randomInt(-28,28,rng),-r.width/3,r.width/3); const ny=clamp(pos.y+randomInt(-10,10,rng),-40,40); setPos({x:nx,y:ny}); setMoves(v=>v+1); setMsg(lines[moves%lines.length]);}}><label className='smooth' style={{transform:`translate(${pos.x}px,${pos.y}px)`}}><input type='checkbox' onChange={()=>moves>=4?onPass():setMsg('它还在紧张移动中。')}/> 我不是机器人</label></div></div>;
}

export function Level2ImageCaptcha({ levelSeed, onPass, onFail }: LevelProps) {
  const rng = useMemo(() => createSeededRandom(levelSeed), [levelSeed]);
  const cards = useMemo(()=>shuffle([
    {k:'cat1',t:'橘猫',ok:true,tip:'这确实是一只猫。'},{k:'cat2',t:'奶牛猫',ok:true,tip:'这确实是一只猫。'},
    {k:'hat',t:'猫耳帽',ok:false,tip:'这是帽子，不是猫。'},{k:'owl',t:'猫头鹰',ok:false,tip:'名字里有猫，但不是猫。'},
    {k:'toy',t:'机器猫玩具',ok:false,tip:'这是玩具，不是活体猫。'},{k:'dog',t:'狗',ok:false,tip:'这是狗。'},{k:'fish',t:'鱼',ok:false,tip:'这是鱼。'},{k:'empty',t:'空白卡',ok:false,tip:'这里什么都没有。'},{k:'cup',t:'猫爪杯',ok:false,tip:'杯子不是猫。'}
  ],rng),[rng]);
  const [sel,setSel]=useState<string[]>([]); const [msg,setMsg]=useState('');
  return <div><h3>任务：从 9 张卡片中选择所有真正的猫</h3><div className='grid'>{cards.map(c=><button key={c.k} className={`tile ${sel.includes(c.k)?'on':''}`} onClick={()=>{setSel(v=>v.includes(c.k)?v.filter(x=>x!==c.k):[...v,c.k]);setMsg(c.tip);}}>{c.t}</button>)}</div><div className='feedback'>{msg||'点击卡片查看解释。'}</div><button className='btn' onClick={()=>{const wrong=cards.filter(c=>sel.includes(c.k)&&!c.ok).length; const miss=cards.filter(c=>c.ok&&!sel.includes(c.k)).length; if(!wrong&&!miss) onPass(); else onFail(`你选中了 ${wrong} 个像猫但不是猫的东西，漏选 ${miss} 只真猫。`,{resetLevel:true});}}>验证</button></div>;
}

export function Level3RunawayAgree({ levelSeed, onPass }: LevelProps) { const rng=useMemo(()=>createSeededRandom(levelSeed),[levelSeed]); const [esc,setEsc]=useState(0); const [p,setP]=useState({x:0,y:0}); const stop=esc>=5; return <div><h3>任务：点击“同意”按钮</h3><div className='feedback'>{stop?'它累了，现在可以点中。':'它会躲避 5 次，然后停下。'}</div><button className='btn smooth' style={{transform:`translate(${p.x}px,${p.y}px)`}} onMouseEnter={(e)=>{if(stop)return;const r=(e.currentTarget.parentElement as HTMLElement).getBoundingClientRect();setP({x:clamp(p.x+randomInt(-40,40,rng),-r.width/4,r.width/4),y:clamp(p.y+randomInt(-20,20,rng),-40,40)});setEsc(v=>v+1);}} onClick={()=>stop&&onPass()}>同意</button></div>; }

export function Level4Terms({ levelSeed, onPass, onFail }: LevelProps) { const rng=useMemo(()=>createSeededRandom(levelSeed),[levelSeed]); const [extend,setExtend]=useState(false); const [ready,setReady]=useState(false); const [left,setLeft]=useState(3); useEffect(()=>{if(ready)setLeft(0)},[ready]); return <div><h3>任务：滚动协议到底部并勾选“我已阅读”</h3><div className='terms' onScroll={e=>{const el=e.currentTarget; if(el.scrollTop+el.clientHeight>=el.scrollHeight-8&&!extend){setExtend(true);return;} if(extend&&el.scrollTop+el.clientHeight>=el.scrollHeight-2) setReady(true); else setLeft(Math.max(1,Math.ceil((el.scrollHeight-(el.scrollTop+el.clientHeight))/24)));}}>{Array.from({length:22}).map((_,i)=><p key={i}>第{i+1}条：本协议仅用于游戏内验证体验。</p>)}{extend&&<p>补充条款：等等，还有最后一行。</p>}</div><div className='feedback'>{ready?'已完成阅读，可勾选。':`你还差最后 ${left} 行没有读完。`}</div><label><input disabled={!ready} type='checkbox' onChange={()=>ready?onPass():onFail('你还没读到底。')}/> 我已阅读</label></div>; }

export function Level5Slider({ onPass }: LevelProps) { const [v,setV]=useState(0); const [bounced,setBounced]=useState(false); return <div><h3>任务：把滑块拖到最右侧</h3><div className='feedback'>{!bounced?'接近终点会变重，并且只回弹一次。':'已回弹一次，现在可直接拖到终点。'}</div><input type='range' min={0} max={100} value={v} onChange={e=>{let nv=+e.target.value;if(nv>80)nv=Math.min(100,v+2);setV(nv);}} onMouseUp={()=>{if(v>=90&&!bounced){setV(82);setBounced(true);} if(v>=100)onPass();}}/>{v>=100&&onPass()}</div>; }

export function Level6RealButton({ onPass, onFail }: LevelProps) { return <div><h3>任务：点击页面上的“继续”按钮</h3><div className='btnGrid'><button disabled className='btn subtle'>继续</button><button className='btn subtle' onClick={()=>onFail('你点到了一个过于积极的按钮。',{resetLevel:true})}>继续。</button><button className='btn subtle' onClick={()=>onFail('这个按钮看起来像继续，但它不够纯粹。',{resetLevel:true})}>继 续</button><button className='btn subtle fakeHover' onClick={()=>onFail('系统推荐不一定真心推荐。',{resetLevel:true})}>继续</button><button className='btn good' onClick={onPass}>继续</button></div><div className='feedback'>提示：找“文字完全匹配且可点击”的那个。</div></div>; }

export function Level7CaptchaInput({ levelSeed, onPass, onFail }: LevelProps) { const rng=useMemo(()=>createSeededRandom(levelSeed),[levelSeed]); const code=useMemo(()=>randomChoice(['HUMAN','NOTBOT','TRUST','HELLO'],rng),[rng]); const [fix,setFix]=useState(false); const [v,setV]=useState(''); return <div><h3>任务：输入验证码 {code}</h3><input value={v} onChange={e=>setV(fix?e.target.value:e.target.value.toLowerCase())}/><label className='switch'><input type='checkbox' checked={fix} onChange={e=>setFix(e.target.checked)}/> 关闭自动纠正</label><div className='feedback'>{fix?'输入框已恢复正常。':'输入框当前会自动小写化。'}</div><button className='btn' onClick={()=>v===code?onPass():onFail('输入内容在进入系统前发生了变化。')}>验证</button></div>; }

export function Level8Patience({ onPass, onFail }: LevelProps) { const [t,setT]=useState(5); useEffect(()=>{const id=setInterval(()=>setT(v=>v-1),1000);return()=>clearInterval(id)},[]); useEffect(()=>{if(t<=0)onPass();},[t,onPass]); return <div><h3>任务：等待倒计时结束，不要点击按钮</h3><div className='feedback'>剩余 {Math.max(t,0)} 秒</div><button className='btn warn glowSoft' onClick={()=>{setT(5);onFail('你点击了诱惑按钮，耐心值归零。',{resetLevel:true});}}>点击可加速</button></div>; }

export function Level9Sort({ onPass, onFail }: LevelProps) { const ans=['睁眼','关闹钟','再躺一分钟','起床','洗漱','出门']; const [arr,set]=useState(shuffle(ans,Math.random)); const [drag,setDrag]=useState<number|null>(null); return <div><h3>任务：按“早上起床流程”排序</h3>{arr.map((x,i)=><div key={x} className='sortItem' draggable onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag===null)return;const a=[...arr];const[it]=a.splice(drag,1);a.splice(i,0,it);set(a);}}>{x}</div>)}<button className='btn' onClick={()=>{const idx=arr.findIndex((x,i)=>x!==ans[i]); idx===-1?onPass():onFail(`排序节奏不太对，系统要求重新校准。`,{resetLevel:true});}}>验证</button></div>; }

export function Level10FakePermission({ onPass, onFail }: LevelProps) { const opts=[['读取我的脑电波',false],['上传我的拖延症',false],['记录我的发呆质量',false],['仅保存本局游戏进度',true],['仅播放游戏内音效',true]] as const; const [s,set]=useState<string[]>([]); return <div><h3>任务：只勾选安全的游戏内授权选项</h3>{opts.map(([x])=><label key={x} className='switch'><input type='checkbox' checked={s.includes(x)} onChange={()=>set(v=>v.includes(x)?v.filter(n=>n!==x):[...v,x])}/>{x}</label>)}<button className='btn' onClick={()=>{const bad=opts.filter(([x,safe])=>s.includes(x)&&!safe).length; const miss=opts.filter(([x,safe])=>safe&&!s.includes(x)).length; (!bad&&!miss)?onPass():onFail(`你授权得太慷慨了。`,{resetLevel:true});}}>确认</button></div>; }

export function Level11InvisibleCaptcha({ levelSeed, onPass, onFail }: LevelProps) { const rng=useMemo(()=>createSeededRandom(levelSeed),[levelSeed]); const code=useMemo(()=>randomChoice(['NOTBOT','HUMAN','TRUSTME'],rng),[rng]); const [hover,setHover]=useState(0); useEffect(()=>{if(hover<=0)return;const id=setInterval(()=>setHover(v=>v+0.2),200);return()=>clearInterval(id)},[hover]); const [v,setV]=useState(''); const clear=hover>=2; return <div><h3>任务：输入隐藏验证码</h3><p className='feedback'>请靠近观察。</p><div className='captchaGhost' style={{opacity:clear?0.95:0.25}} onMouseEnter={()=>setHover(0.1)} onMouseLeave={()=>setHover(0)}>{code}</div><input value={v} onChange={e=>setV(e.target.value)}/><button className='btn' onClick={()=>v===code?onPass():onFail('你输入的并非当前可用验证码。')}>验证</button></div>; }

export function Level12Final({ onPass, onFail }: LevelProps) { const [cool,setCool]=useState(3); useEffect(()=>{if(cool<=0)return;const id=setInterval(()=>setCool(v=>v-1),1000);return()=>clearInterval(id)},[cool]); const ready=cool<=0; return <div><h3>任务：点击“完成验证”</h3><button className='btn giant warn' onClick={()=>ready?onPass():onFail('你在冷却结束前暴露了急躁。')}>{ready?'现在可以完成验证':`立即完成验证（冷却 ${cool}s）`}</button><div className='feedback'>{ready?'冷却结束，点击即可通关。':'请等待 3 秒冷却。'}</div></div>; }

export const allLevels = [Level1Checkbox,Level2ImageCaptcha,Level3RunawayAgree,Level4Terms,Level5Slider,Level6RealButton,Level7CaptchaInput,Level8Patience,Level9Sort,Level10FakePermission,Level11InvisibleCaptcha,Level12Final];
