import { useEffect, useMemo, useState } from 'react';import { LevelProps } from './common';
export function Level1Checkbox({onPass,onFail,onPrank}:LevelProps){const [esc,setEsc]=useState(0);const [pos,setPos]=useState({x:0,y:0});const [start]=useState(Date.now());const can=esc>=5||Date.now()-start>2000;return <div onMouseMove={(e)=>{if(can||esc>=5)return;const r=(e.currentTarget as HTMLDivElement).getBoundingClientRect();const cx=r.left+r.width/2+pos.x,cy=r.top+r.height/2+pos.y;const d=Math.hypot(e.clientX-cx,e.clientY-cy);if(d<120){setPos({x:(Math.random()-0.5)*100,y:(Math.random()-0.5)*40});setEsc(v=>v+1);onPrank('复选框逃跑了');}}} className='levelBox'><label style={{transform:`translate(${pos.x}px,${pos.y}px)`}}><input type='checkbox' onClick={()=>{if(Date.now()-start<600){onFail('你点得太着急了，很像机器人');return;} if(can) onPass();}}/> 我不是机器人</label></div>}
export function Level2ImageCaptcha({onPass,onFail}:LevelProps){const items=['猫','猫头鹰','老虎','狗','猫耳帽','机器人猫','空白','鱼','键盘'];const [s,set]=useState<number[]>([]);const t=[0,5];return <div><div className='grid'>{items.map((x,i)=><button key={i} className={`tile ${s.includes(i)?'on':''}`} onClick={()=>set(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i])}>{x}</button>)}</div><button className='btn' onClick={()=>JSON.stringify([...s].sort())===JSON.stringify(t)?onPass():onFail('系统：你被“猫头鹰”骗到了吗？')}>验证</button></div>}
export function Level3RunawayAgree({onPass,onFail,onPrank}:LevelProps){const [n,setN]=useState(0);const [p,setP]=useState({x:0,y:0});return <div className='row'><button className='btn' style={{transform:`translate(${p.x}px,${p.y}px)`}} onMouseEnter={()=>{setP({x:(Math.random()-0.5)*120,y:(Math.random()-0.5)*40});onPrank('同意按钮再次逃跑');}} onClick={()=>onFail('它不想这么快同意。')}>同意</button><button className='btn subtle' onClick={()=>setN(v=>v+1)}>不同意</button>{n>=3&&<button className='btn good' onClick={onPass}>谨慎同意</button>}</div>}
export function Level4Terms({onPass,onFail}:LevelProps){const [b,setB]=useState(false);const [ok,setOk]=useState(false);useEffect(()=>{if(b){const t=setTimeout(()=>setOk(true),1000);return()=>clearTimeout(t)}},[b]);return <div><div className='terms' onScroll={e=>{const el=e.currentTarget; if(el.scrollTop+el.clientHeight>=el.scrollHeight-2) setB(true);}}>{Array.from({length:30}).map((_,i)=><p key={i}>第{i+1}条：你同意阅读你没有阅读的内容。</p>)}</div><label><input type='checkbox' onChange={()=>ok?onPass():onFail('你甚至没有假装读完。')}/> 我已认真阅读并理解以上内容</label></div>}
export function Level5Slider({onPass,onPrank}:LevelProps){const [v,setV]=useState(0);const [show,setShow]=useState(false);return <div><input type='range' min={0} max={100} value={v} onChange={e=>setV(+e.target.value)} onMouseUp={()=>{if(v>90){setV(82);setShow(true);onPrank('滑块反弹了一下')}}}/>{show&&<button className='btn tiny' onClick={onPass}>其实这样也算</button>}</div>}
export function Level6RealButton({onPass,onFail,onPrank}:LevelProps){const fake=['继续','继续.','继 续','确认','确定','我确定我想继续','请不要点我','点我也没用'];return <div className='btnGrid'>{fake.map((x,i)=><button key={i} className='btn subtle' onClick={()=>{onFail('这不是那个按钮。');onPrank('假按钮干扰成功');}}>{x}</button>)}<button className='btn micro good' onClick={onPass}>{'继续 '}</button></div>}
export function Level7CaptchaInput({onPass,onFail}:LevelProps){const [lock,setLock]=useState(false);const [v,setV]=useState('');return <div><p>请输入：HUMAN</p><input value={v} onChange={e=>setV(lock?e.target.value:e.target.value.toLowerCase())}/><button className='btn tiny' onClick={()=>setLock(true)}>锁定大小写</button><button className='btn' onClick={()=>v==='HUMAN'?onPass():onFail('系统要求大写，但你的输入框有自己的想法。')}>验证</button></div>}
export function Level8Patience({onPass,onFail}:LevelProps){const [t,setT]=useState(0);useEffect(()=>{const i=setInterval(()=>setT(v=>v+1),1000);return()=>clearInterval(i)},[]);useEffect(()=>{if(t>=5)onPass();},[t,onPass]);return <div><button className='btn warn' onClick={()=>onFail('机器人最喜欢不听话。')}>我偏要点</button><div className='progress'><div className='bar' style={{width:`${Math.min((t/5)*100,100)}%`}}/></div><p>冲动检测中...</p></div>}
export function Level9Sort({onPass,onFail}:LevelProps){const ans=['再睡一会儿','后悔','吃饭','学习','发呆','睡觉'];const [arr,set]=useState(['吃饭','睡觉','学习','发呆','后悔','再睡一会儿']);const [drag,setDrag]=useState<number|null>(null);return <div>{arr.map((x,i)=><div key={x} draggable onDragStart={()=>setDrag(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(drag===null)return;const a=[...arr];const [it]=a.splice(drag,1);a.splice(i,0,it);set(a);setDrag(null);}} className='sortItem'>{x}</div>)}<button className='btn' onClick={()=>JSON.stringify(arr)===JSON.stringify(ans)?onPass():onFail('这顺序太自律了，不像人类。')}>验证</button></div>}
export function Level10FakePermission({onPass,onFail}:LevelProps){const opts=['同意使用我的鼠标轨迹训练 AI','同意让系统读取我的脑电波','同意把我的拖延症上传云端','同意只授权游戏内虚构数据','同意系统每天夸我一次'];const [s,set]=useState<number[]>([]);return <div>{opts.map((x,i)=><label key={i} className='switch'><input type='checkbox' checked={s.includes(i)} onChange={()=>set(v=>v.includes(i)?v.filter(n=>n!==i):[...v,i])}/>{x}</label>)}<button className='btn' onClick={()=>JSON.stringify([...s].sort())===JSON.stringify([3,4])?onPass():onFail('你授权得太豪迈了。')}>确认</button></div>}
export function Level11InvisibleCaptcha({onPass,onFail}:LevelProps){const [h,setH]=useState(false);const [c,setC]=useState(0);const [v,setV]=useState('');useEffect(()=>{let t:ReturnType<typeof setInterval>|undefined;if(h)t=setInterval(()=>setC(x=>Math.min(x+1,20)),100);return()=>t&&clearInterval(t)},[h]);const opacity=0.05+c/20*0.8;return <div><div className='captchaGhost' style={{opacity}} onMouseEnter={()=>setH(true)} onMouseLeave={()=>setH(false)}>NOTBOT</div><input value={v} onChange={e=>setV(e.target.value)}/><button className='btn' onClick={()=>v==='NOTBOT'?onPass():onFail('你看到的可能是幻觉。')}>验证</button></div>}
export function Level12Final({onPass,onFail}:LevelProps){return <div><button className='btn giant warn' onClick={()=>onFail('太急了，扣一分。')}>立即完成验证</button><button className='tinyLink' onClick={onPass}>我选择慢慢完成验证</button></div>}
